using System.Collections.ObjectModel;
using WinStudio.Common;

namespace WinStudio.Editor;

public sealed class TimelineViewModel
{
    public TimelineViewModel(long durationTicks)
    {
        DurationTicks = Math.Max(0, durationTicks);
        TrimOutTicks = DurationTicks;
    }

    public long DurationTicks { get; } 
    public long TrimInTicks { get; private set; }
    public long TrimOutTicks { get; private set; }
    public ObservableCollection<ZoomKeyframe> ZoomKeyframes { get; } = [];

    public void SetTrim(TrimHandle handle, long ticks)
    {
        var clamped = Math.Clamp(ticks, 0, DurationTicks);
        if (handle == TrimHandle.In)
        {
            TrimInTicks = Math.Min(clamped, TrimOutTicks);
            return;
        }

        TrimOutTicks = Math.Max(clamped, TrimInTicks);
    }

    public void AddManualZoom(ZoomKeyframe keyframe)
    {
        ZoomKeyframes.Add(keyframe with { IsAutoGenerated = false });
        SortKeyframes();
    }

    public void MoveKeyframe(int index, long newStartTicks, long newEndTicks)
    {
        if (index < 0 || index >= ZoomKeyframes.Count)
        {
            throw new ArgumentOutOfRangeException(nameof(index));
        }

        var current = ZoomKeyframes[index];
        ZoomKeyframes[index] = current with
        {
            StartTicks = Math.Clamp(newStartTicks, 0, DurationTicks),
            EndTicks = Math.Clamp(newEndTicks, 0, DurationTicks)
        };

        SortKeyframes();
    }

    public bool DeleteKeyframe(int index)
    {
        if (index < 0 || index >= ZoomKeyframes.Count)
        {
            return false;
        }

        ZoomKeyframes.RemoveAt(index);
        return true;
    }

    private void SortKeyframes()
    {
        var ordered = ZoomKeyframes.OrderBy(static k => k.StartTicks).ToArray();
        ZoomKeyframes.Clear();
        foreach (var item in ordered)
        {
            ZoomKeyframes.Add(item);
        }
    }
}

