namespace WinStudio.Common;

public sealed record ZoomKeyframe
{
    public required long StartTicks { get; init; }
    public required long EndTicks { get; init; }
    public required RectF TargetRect { get; init; }
    public EasingType EasingIn { get; init; } = EasingType.EaseInOutCubic;
    public EasingType EasingOut { get; init; } = EasingType.EaseOutCubic;
    public bool IsAutoGenerated { get; init; } = true;
}

