using WinStudio.Common;

namespace WinStudio.Processing;

public sealed class VideoCompositor
{
    private readonly CursorHighlighter _cursorHighlighter = new();

    public Task<IReadOnlyList<ProcessedVideoFrame>> ProcessAsync(
        IReadOnlyList<RawVideoFrame> frames,
        IReadOnlyList<ZoomKeyframe> zoomKeyframes,
        IReadOnlyList<CursorEvent> cursorEvents,
        int outputWidth,
        int outputHeight,
        IProgress<double>? progress = null,
        CancellationToken cancellationToken = default)
    {
        if (outputWidth <= 0 || outputHeight <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(outputWidth), "Output dimensions must be positive.");
        }

        var output = new List<ProcessedVideoFrame>(frames.Count);
        for (var i = 0; i < frames.Count; i++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var frame = frames[i];
            var keyframe = FindKeyframe(frame.TimestampTicks, zoomKeyframes, frame.Width, frame.Height);
            var cursorState = _cursorHighlighter.GetRenderState(frame.TimestampTicks, cursorEvents);
            var copy = new byte[frame.PixelBuffer.Length];
            Array.Copy(frame.PixelBuffer, copy, frame.PixelBuffer.Length);

            output.Add(
                new ProcessedVideoFrame(
                    frame.TimestampTicks,
                    outputWidth,
                    outputHeight,
                    copy,
                    keyframe.TargetRect,
                    cursorState.Scale,
                    cursorState.Opacity));

            progress?.Report((i + 1d) / frames.Count);
        }

        return Task.FromResult<IReadOnlyList<ProcessedVideoFrame>>(output);
    }

    private static ZoomKeyframe FindKeyframe(long timestampTicks, IReadOnlyList<ZoomKeyframe> keyframes, int width, int height)
    {
        var fullScreen = new RectF(0f, 0f, width, height);

        for (var i = 0; i < keyframes.Count; i++)
        {
            var keyframe = keyframes[i];
            if (timestampTicks >= keyframe.StartTicks && timestampTicks <= keyframe.EndTicks)
            {
                var duration = keyframe.EndTicks - keyframe.StartTicks;
                if (duration <= 0)
                {
                    return keyframe;
                }

                // Interpolate from the previous keyframe's destination to this one.
                // This gives smooth animated transitions instead of instant snaps.
                var prevRect = i > 0 ? keyframes[i - 1].TargetRect : fullScreen;
                var t = (float)(timestampTicks - keyframe.StartTicks) / duration;
                var easedT = EasingFunctions.Evaluate(keyframe.EasingIn, t);
                var interpolatedRect = LerpRect(prevRect, keyframe.TargetRect, easedT);
                return keyframe with { TargetRect = interpolatedRect };
            }
        }

        return new ZoomKeyframe
        {
            StartTicks = timestampTicks,
            EndTicks = timestampTicks,
            TargetRect = fullScreen,
            EasingIn = EasingType.Linear,
            EasingOut = EasingType.Linear,
            IsAutoGenerated = true
        };
    }

    private static RectF LerpRect(RectF from, RectF to, float t)
    {
        return new RectF(
            from.X + ((to.X - from.X) * t),
            from.Y + ((to.Y - from.Y) * t),
            from.Width + ((to.Width - from.Width) * t),
            from.Height + ((to.Height - from.Height) * t));
    }
}
