using WinStudio.Common;

namespace WinStudio.Processing;

public sealed class ZoomRegionGenerator
{
    // ── Timing ──────────────────────────────────────────────────────────────
    private static readonly long IdleTimeoutTicks    = TimeSpan.FromSeconds(2.0).Ticks;
    private static readonly long ZoomInTicks         = TimeSpan.FromMilliseconds(300).Ticks;
    private static readonly long ZoomOutTicks        = TimeSpan.FromMilliseconds(500).Ticks;
    private static readonly long PanKeyframeGapTicks = TimeSpan.FromMilliseconds(16).Ticks; // ~60 fps

    // ── Size ─────────────────────────────────────────────────────────────────
    private const float MinTargetWidthRatio   = 0.25f;  // never zoom more than 4×
    private const float PanThresholdFraction  = 0.0015f; // 0.15 % of capture width
    // Intensity multiplier: lower = less aggressive zoom = wider view (less right-side crop).
    // 0.55 gives ~1.77× at default intensity 1.4 (window ≈ 56 % of screen width),
    // matching the effective zoom the previous code produced in its steady-state.
    private const float ZoomScaleMultiplier   = 0.55f;

    public IReadOnlyList<ZoomKeyframe> Generate(
        IReadOnlyList<CursorEvent> events,
        int captureWidth,
        int captureHeight,
        float zoomIntensity = 1.4f,
        float zoomSensitivity = 1.2f,
        float followSpeed = 1.15f)
    {
        if (captureWidth <= 0 || captureHeight <= 0)
            throw new ArgumentOutOfRangeException(nameof(captureWidth), "Capture dimensions must be positive.");

        if (events.Count == 0)
            return [];

        var ordered       = events.OrderBy(static e => e.TimestampTicks).ToArray();
        var safeIntensity = Math.Clamp(zoomIntensity, 0.6f, 2.2f);
        var zoomScale     = Math.Clamp(1.0f + safeIntensity * ZoomScaleMultiplier, 1.1f, 2.5f);
        var thresholdX    = Math.Max(2f, captureWidth  * PanThresholdFraction);
        var thresholdY    = Math.Max(2f, captureHeight * PanThresholdFraction);
        var fullScreen    = new RectF(0f, 0f, captureWidth, captureHeight);

        var timeline         = new List<ZoomKeyframe>(256);
        var isZoomed         = false;
        var cameraRect       = fullScreen;         // current EMITTED camera window
        var timelineTick     = ordered[0].TimestampTicks;
        var lastActivityTick = ordered[0].TimestampTicks;
        var lastPanTick      = ordered[0].TimestampTicks;
        // Latest cursor position seen — updated on every Move.  Used so that if
        // the cursor moves during the zoom-in animation (when gap never passes),
        // the subsequent Hold still lands at the correct camera position.
        var lastCursorX      = ordered[0].X;
        var lastCursorY      = ordered[0].Y;

        // Emit a static hold segment from timelineTick → endTick.
        void Hold(long endTick)
        {
            if (endTick > timelineTick)
                timeline.Add(new ZoomKeyframe
                {
                    StartTicks = timelineTick, EndTicks = endTick,
                    TargetRect = cameraRect,
                    EasingIn = EasingType.Linear, EasingOut = EasingType.Linear,
                    IsAutoGenerated = true
                });
            timelineTick = endTick;
        }

        // Emit an animated transition and advance the write cursor.
        void Transition(long start, long end, RectF target, EasingType easing)
        {
            if (end > start)
                timeline.Add(new ZoomKeyframe
                {
                    StartTicks = start, EndTicks = end,
                    TargetRect = target,
                    EasingIn = easing, EasingOut = easing,
                    IsAutoGenerated = true
                });
            timelineTick = end;
        }

        // Camera window centered on cursor, same size, clamped inside capture.
        RectF FollowCursor(float x, float y) =>
            new RectF(x - cameraRect.Width / 2f, y - cameraRect.Height / 2f,
                      cameraRect.Width, cameraRect.Height)
                .ClampWithin(captureWidth, captureHeight);

        // Apply the latest known cursor position to cameraRect before a Hold/ZoomOut.
        // This handles the case where the cursor moved during the zoom-in window but
        // the pan gap never fired, so cameraRect was never updated in the loop.
        void FlushCursorToCamera()
        {
            var desired = FollowCursor(lastCursorX, lastCursorY);
            var dx = MathF.Abs(desired.X - cameraRect.X);
            var dy = MathF.Abs(desired.Y - cameraRect.Y);
            if (dx > thresholdX || dy > thresholdY)
                cameraRect = desired;
        }

        // Close any open hold, animate to full-screen, update state.
        void ZoomOut(long fromTick)
        {
            FlushCursorToCamera();   // apply any buffered cursor movement first
            Hold(fromTick);
            Transition(fromTick, fromTick + ZoomOutTicks, fullScreen, EasingType.EaseInOutCubic);
            cameraRect = fullScreen;
            isZoomed   = false;
        }

        foreach (var evt in ordered)
        {
            var tick      = evt.TimestampTicks;
            var eventType = evt.EventType;
            var isClick   = IsActivationEvent(eventType);
            var isMove    = eventType == CursorEventType.Move;
            var isKey     = eventType == CursorEventType.KeyPress;

            // ── Idle-timeout check ────────────────────────────────────────────
            // Must happen before handling the current event so keyframe times stay
            // monotone: zoom-out is anchored to lastActivityTick + timeout, NOT tick.
            if (isZoomed && tick > lastActivityTick + IdleTimeoutTicks)
                ZoomOut(lastActivityTick + IdleTimeoutTicks);

            // ── Not zoomed + activation → zoom in centered on cursor ──────────
            if (!isZoomed && isClick && evt.X >= 0f && evt.Y >= 0f)
            {
                var target = BuildZoomRegion(evt.X, evt.Y, zoomScale, captureWidth, captureHeight);
                Hold(tick);
                Transition(tick, tick + ZoomInTicks, target, EasingType.EaseOutCubic);
                cameraRect       = target;
                isZoomed         = true;
                lastActivityTick = tick;
                lastPanTick      = timelineTick;
                continue;
            }

            // ── Zoomed + move → pan camera to follow cursor ───────────────────
            if (isZoomed && isMove)
            {
                lastActivityTick = tick;
                lastCursorX      = evt.X;
                lastCursorY      = evt.Y;

                // Throttle Hold emissions to ~30 fps.  cameraRect is only updated
                // when we actually emit, so the threshold check below correctly
                // measures cumulative distance since the LAST HOLD — not since the
                // last individual event.  This fixes slow-movement tracking where
                // the old code updated cameraRect on every event, resetting the
                // delta to near-zero and causing moved=false perpetually.
                if (tick - lastPanTick >= PanKeyframeGapTicks)
                {
                    var desired = FollowCursor(evt.X, evt.Y);
                    var dx      = MathF.Abs(desired.X - cameraRect.X);
                    var dy      = MathF.Abs(desired.Y - cameraRect.Y);
                    if (dx > thresholdX || dy > thresholdY)
                    {
                        Hold(tick);
                        cameraRect  = desired;
                    }
                    // Always advance lastPanTick even when camera didn't move —
                    // prevents a burst of identical holds after a static period.
                    lastPanTick = tick;
                }
                continue;
            }

            // ── Zoomed + activation → reset idle timer, snap to cursor if far ─
            if (isZoomed && isClick)
            {
                lastActivityTick = tick;
                lastCursorX      = evt.X;
                lastCursorY      = evt.Y;
                var desired = FollowCursor(evt.X, evt.Y);
                var dx      = MathF.Abs(desired.X - cameraRect.X);
                var dy      = MathF.Abs(desired.Y - cameraRect.Y);
                if (dx > thresholdX || dy > thresholdY)
                {
                    Hold(tick);
                    cameraRect  = desired;
                    lastPanTick = tick;
                }
                continue;
            }

            // ── Zoomed + key press → keep zoom alive ──────────────────────────
            if (isZoomed && isKey)
            {
                lastActivityTick = tick;
            }
        }

        // Seal any remaining zoomed state at end of recording.
        if (isZoomed)
            ZoomOut(Math.Max(timelineTick, lastActivityTick + IdleTimeoutTicks));

        return timeline.Any(k => k.TargetRect.Width < captureWidth - 1f
                               || k.TargetRect.Height < captureHeight - 1f)
            ? timeline
            : [];
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static bool IsActivationEvent(CursorEventType eventType) =>
        eventType is CursorEventType.LeftDown or CursorEventType.RightDown or CursorEventType.Scroll;

    private static RectF BuildZoomRegion(
        float cursorX, float cursorY,
        float zoomScale,
        int captureWidth, int captureHeight)
    {
        if (zoomScale <= 1.01f)
            return new RectF(0f, 0f, captureWidth, captureHeight);

        var width  = Math.Max(captureWidth  * MinTargetWidthRatio, captureWidth  / zoomScale);
        var height = Math.Max(captureHeight * MinTargetWidthRatio, captureHeight / zoomScale);
        return RectF.FromCenter(cursorX, cursorY, width, height)
            .ClampWithin(captureWidth, captureHeight);
    }
}
